# Generated by Django 3.2.9 on 2021-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211112_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='social_media_links',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
